<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-11 15:04
=======
# Generated by Django 3.2 on 2023-07-12 10:24
>>>>>>> 2e3dd555577cb1578d8674b826d7b18050ae3557

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=159, verbose_name='Категории')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанры')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Movie',
=======
            name='Movies',
>>>>>>> 2e3dd555577cb1578d8674b826d7b18050ae3557
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=1980, verbose_name='Год выпуска')),
                ('original_title', models.CharField(max_length=100, verbose_name='Название на японском')),
                ('age_permissions', models.CharField(max_length=50, verbose_name='Возрастной рейтинг')),
<<<<<<< HEAD
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='жанры')),
                ('themes', models.ManyToManyField(to='movies.theme', verbose_name='темы')),
=======
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='жанры')),
                ('themes', models.ManyToManyField(to='movies.Theme', verbose_name='темы')),
>>>>>>> 2e3dd555577cb1578d8674b826d7b18050ae3557
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Анимы',
            },
        ),
    ]
